### ISSUE TITLE
"cannot make memory view because object does not have the buffer interface"

### ISSUE THREAD

**Issue by netanelkl** [coinbase/coinbase-python#10]
requests using the python lib started breaking.
I'm using coinbase 2.8.1, python 2.7.9.

and I noticed, after upgrading my packages (I believe specifically the requests package from 2.7.0 to 2.8.1), that I started receiving
"cannot make memory view because object does not have the buffer interface".
I believe the reason is a change in either the requests package or the encompassed urllib3 lib.
I did some debugging into it, and noticed that the body of the request (actually the headers are being converted to a memoryview. Problem is, it doesnt support unicode (as far as I could tell).
I traced the exception down to requests.packages.urllib3.contrib.pyopenssl.py
I noticed that if I remove:
from __future__ import unicode_literals
on the coinbase library so that str types would be passed in the header keys, the problem disappears.

**Comment by jorilallo** [comment]
https://github.com/kennethreitz/requests/issues/2818 There seems to be a related requests issue

**Comment by netanelkl** [comment]
I'm making a PR to fix this, in case you're interested, many ways to go about it, though.

**Comment by jorilallo** [comment]
@netanelkl sorry for the delay, I'll merge that in. Thanks for the investigation and PR around this, really appreciate it!

**Comment by jorilallo** [comment]
Now included in published 2.0.2

**Comment by netanelkl** [comment]
Great, thanks!!
Of course :)
