### ISSUE TITLE
Accessing the "raw" JSON document

### ISSUE THREAD

**Issue by PierreRochard** [coinbase/coinbase-python#16]
Is there a way to do this without adding these two lines: https://github.com/PierreRochard/coinbase-python/commit/01d4e69fb937fc55141b504371e61eb4b339c121 ?

Thanks,

Pierre

**Comment by sds** [comment]
Hey @PierreRochard, there is not currently a public interface exposed to fetch the JSON object directly. However, you can call [`_get(...)`](https://github.com/coinbase/coinbase-python/blob/c9ab9d0f7f232849cee64f4d3c2bdc338c2394f9/coinbase/wallet/client.py#L128-L129) directly and then get the JSON from the response object by calling [`json()`](https://github.com/coinbase/coinbase-python/blob/c9ab9d0f7f232849cee64f4d3c2bdc338c2394f9/coinbase/wallet/client.py#L141).
