### ISSUE TITLE
API_VERSION warning

### ISSUE THREAD

**Issue by BlueWall** [coinbase/coinbase-python#20]
I am just getting started into using my auth tokens to do operations...

BASE_API_URI = 'https://api.sandbox.coinbase.com/v2'
client = OAuthClient(token.access_token, token.refresh_token, base_api_uri=BASE_API_URI)
cb_user = client.get_current_user()

Then I get the warning...
coinbase/wallet/client.py:149: UserWarning: Please supply API version (YYYY-MM-DD) as CB-VERSION header (https://developers.coinbase.com/api#versioning)

I see that CB-VERSION is set when building the request. Wanted to ask if I am using this properly, and whether I can do something to prevent the warning? Hopefully, as I use this more, I will be able to contribute.

Thanks.

**Comment by maksim-s** [comment]
This is now fixed in 2.0.5. You can provide your version:
`client = OAuthClient(token.access_token, token.refresh_token, base_api_uri=BASE_API_URI, api_version='YYYY-MM-DD')`
