### ISSUE TITLE
create_checkout method on Client class is not taking a dict it's unpacking kwargs

### ISSUE THREAD

**Issue by lordscales91** [coinbase/coinbase-python#22]
the class at coinbase.wallet.client.Client for some its methods is getting the parameters as keyword arguments instead of getting a single positional argument for the dictionary. [Reference](https://github.com/coinbase/coinbase-python/blob/e9a459d3cced7239483f2bb2bc04b68dc7e99add/coinbase/wallet/client.py#L531-L537)

The method signature should be `def create_checkout(self, params):` Or update your documentation to indicated that you need to pass keyword arguments

**Comment by sds** [comment]
Hey @lordscales91, thanks for the report.

Looks like our [documentation](https://developers.coinbase.com/api/v2?python#show-a-checkout) has since been updated to address this issue.
