### ISSUE TITLE
ValueError from None and build_api_error

### ISSUE THREAD

**Issue by aclarembeau** [coinbase/coinbase-python#24]
Hello, 

I recently answered a post on stackoverflow about a strange behaviour of your API
(http://stackoverflow.com/questions/37638359/api-coinbase-valueerror-from-get-buy-price/37646769#37646769). 

There seems to be an internal error (build_api_error seems to confirm my assertion) under some conditions (which I can't reproduce because I'm not the author of the post). 

I suspect that's something related to a network connectivity problem that causes a null JSON file. 
It's why the code throws a `raise ValueError(errmsg("Expecting value", s, err.value)) from None` error. 

It also seems quite related to that other issue: https://github.com/coinbase/coinbase-python/issues/15

I hope it will help :)

**Comment by sds** [comment]
Hey @aclarembeau, thanks for the report!

Closing in favor of the more [general issue](https://github.com/coinbase/coinbase-python/issues/44), which is that the library should improve its error handling for these cases.
