### ISSUE TITLE
how to import CoinbaseAccount?

### ISSUE THREAD

**Issue by tsguo3** [coinbase/coinbase-python#28]
Hi,

I'm having trouble doing
`from coinbase import CoinbaseAccount`

Any ideas why?

**Comment by JohnLZeller** [comment]
@tsguo3 `CoinbaseAccount` is in this package. It seems like you might have stumbled accross some instructions for an old unofficial python client.

Go here for instructions on getting started
https://github.com/coinbase/coinbase-python#api-key--secret
