### ISSUE TITLE
Client.get_historic_prices() documentation missing

### ISSUE THREAD

**Issue by jiyuan312986471** [coinbase/coinbase-python#29]
There is no documentation about [`coinbase.wallet.client.Client.get_historic_prices(**params)`](https://github.com/coinbase/coinbase-python/blob/master/coinbase/wallet/client.py#L206), the indicated URL(https://developers.coinbase.com/api/v2#get-historic-prices) does not valid any more.
Where could i find this method's doc ?

**Comment by johnclause** [comment]
I could not find a documentation either. Does anyone know how to get a wider than 1 hour range, which is returned by default on https://api.coinbase.com/v2/prices/:currency_pair/historic ?

**Comment by lyx-x** [comment]
@johnclause According to https://stackoverflow.com/questions/41987859/coinbase-api-python-client-get-historic-prices, you can use a 'period' argument.

**Comment by sds** [comment]
Hey @jiyuan312986471, we do not provide documentation for this endpoint at this time, as it is not intended for public consumption (but we won't stop you from using it).
