### ISSUE TITLE
Release 2.0.7 for Update price endpoints to support ETH?

### ISSUE THREAD

**Issue by wilsonqin** [coinbase/coinbase-python#30]
Was the latest commit on the master branch never tagged and released as v2.0.7?

Currently a pip install from the Python Package Index will result in 2.0.6 being downloaded which [does not support querying non BTC-USD currency pairs for the client get price methods](https://github.com/coinbase/coinbase-python/commit/f9ed2249865c2012e3b86106dad5f8c6068366ed). Missing two commits up to f9ed224.

EDIT: tagging @maksim-s author of that commit

**Comment by keith24** [comment]
Looks like several issues (#32 #35 #36) could be resolved by updating the pypi package.  Who's in charge around here?

**Comment by Buttars** [comment]
I am currently having issues without the support of ETH and LTC coin due to the pypi package neglecting the feature. Would love to see a package update :)

**Comment by Crupuk** [comment]
@sds  @hugovk  could you please take a look ?
Who's in charge of the pypi package ? 

Could you give a date for the 2.0.7 release ? For non US people 2.0.6 is unusable

Thanks

**Comment by hugovk** [comment]
I don't have any access.

**Comment by sds** [comment]
Sorry for the delay, all. 2.0.7 has been uploaded to PyPI. Thanks for your patience!
