### ISSUE TITLE
Cannot install on Rasperry Pi

### ISSUE THREAD

**Issue by NuclearManD** [coinbase/coinbase-python#33]
I always have problems installing on the rasperry pi, failing with error "Python.h: No such file or directory"
I have tried:
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get install python-dev`
`sudo apt-get install python3-dev`
`sudo apt-get install libpython3-dev`
`sudo apt-get install python3.4-dev`
`sudo apt-get install python3.2-dev`
`sudo apt-get install libpython3.4-dev`
and also reinstalling python-dev.

Nothing has worked.

**Comment by D3faIt** [comment]
This did not work for me:
`sudo pip install coinbase`

This worked for me:
`sudo easy_install coinbase`

**Comment by NuclearManD** [comment]
Thankyou, I will try that!
