### ISSUE TITLE
Iterating through paginated results should be built-in

### ISSUE THREAD

**Issue by xanderdunn** [coinbase/coinbase-python#34]
Currently it appears that I have to drop down to manually `GET`ing the `next_uri` strings provided in the `pagination` responses to iterate through the pages of a return value.  

This should be built into this API client's interface.  For example, `account.get_transactions(page=5)`.

**Comment by xanderdunn** [comment]
The [node library](https://github.com/coinbase/coinbase-node) has it built in, see the "Using pagination" section.

**Comment by sds** [comment]
Hey @xanderdunn, thanks for the suggestion.

Would happily accept a PR implementing pagination!

**Comment by xhockey5** [comment]
@sds I just implemented paging in the _get method (client.py). How do I go about submitting a pull request? Can you allow me permissions to make a branch?

**Comment by JohnLZeller** [comment]
@sds seems like this issue can be closed since #77 was merged :)

**Comment by sds** [comment]
Thanks for catching, @JohnLZeller.
