### ISSUE TITLE
PyPI version is out of date

### ISSUE THREAD

**Issue by c4obi** [coinbase/coinbase-python#35]
I was having problems with fetching spot prices for different currency pair combinations but I kept getting only spot prices for bitcoin so I decide to look into the source of the coinbase version that I had installed with pip. It basically had an older version of the source for all the prices api hence the reason for the bad response. Could this be updated?

**Comment by qibinlou** [comment]
+1 The codebase is updated but the release hasn't been kept updated with the codebase.

**Comment by keith24** [comment]
Here's my workaround, cloning the repo and copying it to where pip and easy_install put the module.  This is probably not the right way of doing things, but whatever.  

First, check where `coinbase` was installed:  

```sh
$ ls -1d /usr/local/lib/python*/dist-packages/**/coinbase
/usr/local/lib/python2.7/dist-packages/coinbase-2.0.6-py2.7.egg/coinbase
/usr/local/lib/python3.5/dist-packages/coinbase
```

For me, easy_install installed the python2.7 version, and pip installed the python3.5 version.  Whatever.  

```sh
# Clone repo from github
$ git clone https://github.com/coinbase/coinbase-python.git /tmp/coinbase
# Copy to python2 modules (use directory from above)
$ sudo cp -rp /tmp/coinbase/coinbase/* /usr/local/lib/python2.7/dist-packages/coinbase-2.0.6-py2.7.egg/coinbase
# Copy to python3 modules (use directory from above)
$ sudo cp -rp /tmp/coinbase/coinbase/* /usr/local/lib/python3.5/dist-packages/coinbase
# Set permissions
$ sudo chgrp -R staff  /usr/local/lib/python*/dist-packages/coinbase* &&\
sudo find /usr/local/lib/python*/dist-packages/coinbase* -type f -exec chmod 644 -- {} +
```

Then, check that it works by retrieving the price of ether: 

```python
>>> from coinbase.wallet.client import Client
>>> client = Client(
...   'XXXXXXXXXXXXXXXX', 
...   'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 
...   api_version='2017-11-29' )
>>> client.get_spot_price(currency_pair='ETH-USD').amount
'489.08'
```

If you can't import the module, or the API spits back the current bitcoin price instead, it didn't work.

**Comment by theonewolf** [comment]
@keith24 what you should do (instead of copying like that) is install the experimental version:

`sudo python3 setup.py install`

from inside your git local repository.

That will install it globally on your system.  You may prefer to actually install such an experimental version inside of a `virtualenv` which would be safest.

**Comment by sds** [comment]
2.0.7 was recently released. Sorry for the delay!
