### ISSUE TITLE
Prices are weird

### ISSUE THREAD

**Issue by dbendure** [coinbase/coinbase-python#39]
where does this pull its numbers from?

if use:

file_get_contents('https://api.coinbase.com/v1/prices/sell?qty=1'); 

it returns 1198.27 that matches the sell price on coinbase.com, but: 

print client.get_sell_price(currency_pair = 'BTC-USD').amount

it returns 1192.28.

just showing its off from the actual coinbase site, if its using exchange numbers then that's why its off.

**Comment by dbendure** [comment]
Just checked the exchange its not the same output, so now its just weird.

**Comment by JohnLZeller** [comment]
@dbendure you should switch to the `v2` API. This library uses `v2` as well.
