### ISSUE TITLE
Improve the error handling.

### ISSUE THREAD

**Issue by kitsunde** [coinbase/coinbase-python#44]
When coinbase gives a 502 and presumably any error, it throws a `TypeError` because it's tries to decode the returned html as json.

This whole library basically assumes coinbase is always returning the right thing, there's no error handling here at all: https://github.com/coinbase/coinbase-python/blob/master/coinbase/wallet/model.py#L301-L315

At a minimum it should return the actual connection issue, these are not type issues.

**Comment by sds** [comment]
Hey @kitsunde, thanks for the suggestion.

Would happily accept a PR implementing improved error handling!
