### ISSUE TITLE
Basic call for ETH-USD returning BTC-USD

### ISSUE THREAD

**Issue by jasonmellone** [coinbase/coinbase-python#47]
Hello 

I am new to the library, but with a very basic piece of code that looks like the following:

```
from coinbase.wallet.client import Client
api_key = "api_key"
api_secret = "api_secret"

client = Client(api_key, api_secret)

currency_code = 'ETH-USD'  # can also use EUR, CAD, etc.

# Make the request
price = client.get_spot_price(currency_code = 'ETH-USD')

print 'Current  price in %s: %s' % (currency_code, price.amount)
```

But it is returning:
`Current  price in ETH-USD: 2615.60`

Which is obviously the BTC-USD price.

What am I doing wrong here?

**Comment by mavieth** [comment]
Same issue.

**Comment by spiliopoulos** [comment]
Take a look at my comment [here](https://stackoverflow.com/questions/43037896/historical-etherium-prices-coinbase-api/43124409#comment73360500_43124409) . It might be that you have not updated your api version.

**Comment by jasonmellone** [comment]
I'm on 2.0.6 and getting the issue. I don't think this is a version thing.

**Comment by JLDevOps** [comment]
I'm getting the same issue, but have found the solution.  In your python library, if you installed via pip, go to /site-packages/coinbase/wallet/client.py:

Change this section: 

```
 def get_spot_price(self, **params):
    """https://developers.coinbase.com/api/v2#get-spot-price"""
    response = self._get('v2', 'prices', 'spot', data=params)
    return self._make_api_object(response, APIObject)
```

to:

```
def get_spot_price(self, **params):
"""https://developers.coinbase.com/api/v2#get-spot-price"""

    if 'currency_pair' in params:
        currency_pair = params['currency_pair']
   else:
       currency_pair = 'BTC-USD'
    response = self._get('v2', 'prices', currency_pair, 'spot', data=params)
    return self._make_api_object(response, APIObject)
```

This will get you the correct results for ETH-USD prices.

The problem now is that, the client.py file in the repo has already been updated to the code above, but has not been pushed for pip installation, so either you install the package from the repo or have to go in and change the settings in Python.

**Comment by jasonmellone** [comment]
I chose to modify the client.py directly. Thanks

**Comment by lyx-x** [comment]
This may be a silly question. I installed coinbase via pip(3). The package I got includes the old version of client where the 'currency_pair' isn't used. Will we get a new release or it is recommended to install from source?

**Comment by mego1st** [comment]
Just to update, if anyone is using the code above, changing

`price = client.get_spot_price(currency_code = 'ETH-USD')`

to

`price = client.get_spot_price(currency_pair = 'ETH-USD')`

makes the code work as intended.
