### ISSUE TITLE
Method get_exchange_rates passing params as data

### ISSUE THREAD

**Issue by nmoniz** [coinbase/coinbase-python#49]
Whilst trying out the coinbase python client I noticed that the following code returned incorrect results:
```
client = Client('x','z')
for cur in ['ETH', 'BTC', 'LTC']:
  r = client.get_exchange_rates(currency=cur)
  print('{} => {}'.format(cur, r['currency']))
```
It returned:
```
BTC => ETH
ETH => ETH
LTC => ETH
```
When it should have returned:
```
BTC => BTC
ETH => ETH
LTC => LTC
```
I believe the problem is somewhere in [this](https://github.com/coinbase/coinbase-python/blob/f9ed2249865c2012e3b86106dad5f8c6068366ed/coinbase/wallet/client.py#L174) method. I've tried changing the key-word arguments from `self._get('v2', 'exchange-rates', data=params)
 `  to `self._get('v2', 'exchange-rates', params=params)` and it worked as expected.

The documentation of the `requests` python module (used by `coinbase` to make the actual requests) states that `params` should be used to specify the URL parameters and since the coinbasa API expects a URL parameter `currency` it seems to make sense.

Does this make sense or have I done something wrong?

**Comment by joshblum** [comment]
@nmoniz I ran into the same issue, should be fixed in #54
