### ISSUE TITLE
Coinbase - get_spot_price - historical

### ISSUE THREAD

**Issue by jsartre** [coinbase/coinbase-python#50]
Must be a newbie question. Trying to fetch the historical daily spot prices on coinbase. Using the python implementation of the api as follows.

https://developers.coinbase.com/api/v2#get-spot-price

`price = client.get_spot_price(currency_pair= 'BTC-USD', date='2016-05-10')`

Result (actually today's price):

```
    2016-5-10
{
  "amount": "5613.84",
  "base": "BTC",
  "currency": "USD"
}
```
I get the current spot price. Could anyone shade some light on what I am missing? Thanks!

**Comment by ShakataGaNai** [comment]
The coinbase API doesn't show any historical endpoints (that I've seen). Look around: https://developers.coinbase.com/api/v2#get-spot-price

**Comment by joshblum** [comment]
@jsartre historical data is shown with the `get_spot_price` endpoint but as #49 points out there is a bug with how params are passed on `GET` requests currently. This should be fixed by #54

**Comment by joshblum** [comment]
@jsartre you might also want to checkout the [`get_historic_prices`](https://github.com/coinbase/coinbase-python/blob/f9ed2249865c2012e3b86106dad5f8c6068366ed/coinbase/wallet/client.py#L206) endpoint, it's undocumented but you can checkout the requests made at www.coinbase.com

**Comment by sds** [comment]
#54 has been merged, so you should be able to get historical prices now.
