### ISSUE TITLE
How can I send USD/EUR to an exchange?

### ISSUE THREAD

**Issue by hunsnowboarder** [coinbase/coinbase-python#56]
This is rather a question as I did not find any information about it.

Is it possible to send USD or EUR to an exchange (like Kraken)? If yes, how it is possible? I could not find any information about this.
Thank you very much in advance!

**Comment by sds** [comment]
You'll need to open up the account with the exchange in question and follow their instructions for sending funds. We do not currently support sending fiat currency via the API.
