### ISSUE TITLE
Is it possible to transfer coin -> coin?

### ISSUE THREAD

**Issue by tgoldenberg** [coinbase/coinbase-python#57]
I am trying to transfer between a BTC -> LTC, or ETH -> LTC account.

I am not able to get this to work either via this package or via simple Postman requests.

Here's my approach. After Oauth, I get the client's account IDs. I then get the account for BTC and account for ETH.

I then create a transfer between the two, with a request body like this (below). The code below is in Javascript, but applies as well to Python:
```
const url = `${endpoint}/v2/accounts/${accountId}/transactions`
const type = 'transfer';
const to = 'TO_ID';
const currency = 'BTC';
const amount = '0.00000001';
const response = await request.post(url, { type, to, amount, currency }, { headers });
```
Here, response comes back with a 'Not found' error:

```
{
    "errors": [
        {
            "id": "not_found",
            "message": "Not found"
        }
    ],
    "warnings": [
        {
            "id": "missing_version",
            "message": "Please supply API version (YYYY-MM-DD) as CB-VERSION header",
            "url": "https://developers.coinbase.com/api#versioning"
        }
    ]
}
```
I would appreciate any help in getting this to work! Thank you!

**Comment by sds** [comment]
Hey @tgoldenberg, we do not support cryptocurrency -> cryptocurrency trades on coinbase.com at this time. Consider looking into our exchange [GDAX](https://gdax.com) for such functionality. Thanks!
