### ISSUE TITLE
ConnectionError: HTTPSConnectionPool (host='api.coinbase', port 443): Max retries exceeded with url: /v2/prices/LTC-EUR/sell 

### ISSUE THREAD

**Issue by jojohnjo** [coinbase/coinbase-python#60]
Hey Guys, 

i just run a script for one night, getting the prices of LTC in EUR and was confronted with the following error:

`ConnectionError: HTTPSConnectionPool (host='api.coinbase', port 443): Max retries exceeded with url: /v2/prices/LTC-EUR/sell (Caused by NewConnectionErro ('<urllib3.connection.VerifiedHTTPSConnection object at 0x71f45a10>: Failed to establish a new connection: [Errno -2] Name or service not know',))`

Is there a limit on how often you can push requests? i pushed those requests for 6 hours until i got this error. Does anyone know how one can prevent this error or give me some details about it?

I would be glad for your help! many thanks!;)

**Comment by sds** [comment]
Issue appears to be your hostname: `api.coinbase` is not a valid domain name. You can see the error further down: `[Errno -2] Name or service not known`.

Hope that helps!
