### ISSUE TITLE
Get buy/sell price ignores the currency pair requested

### ISSUE THREAD

**Issue by F1Rumors** [coinbase/coinbase-python#63]
When asking for BTC-USD I am regularly seeing EUR prices come up - though it does at least also report that the currency is EUR when that happens:
`>>> client.get_buy_price(currency_pair='BTC-USD')`
`{
  "amount": "13471.88",
  "base": "BTC",
  "currency": "EUR"
}`
I presume it is actually reporting the most recent BTC price without considering the underlying currency that was traded against it.

Resolution:
- recommend accepting single 'currency' on the price request for the current operation (ie, just get most recent Bitcoin price, tell me the currency it is against)
- recommend API also gets the exchange rate and applies it on a pair price request that is not correctly honoured, and adds 'exchangeRate' and 'exchangeCurrency' elements to the results.

**Comment by jrhee17** [comment]
This seems to work in the master branch

Hopefully you guys can publish a new version based on the current master

**Comment by thepieuvre** [comment]
Same bug with version 2.0.6.
I found a workaround:

```python
   from coinbase.wallet.model import APIObject
   ...
   currency_pair = 'ETH-EUR'
   params = {'currency_pair': currency_pair}
   response = client._get('v2', 'prices', currency_pair, 'buy', data=params)
   price = client._make_api_object(response, APIObject)
```

**Comment by sds** [comment]
Hey @F1Rumors, can you confirm if this is reproducible in version 2.0.7 and open a new issue if that's the case? Thanks!
