### ISSUE TITLE
Get price and get exchange rates not working. 

### ISSUE THREAD

**Issue by murchie85** [coinbase/coinbase-python#65]
Hi when writing a simple python script to test Coinbase Features as per documentation I am getting the following results:

`rates = client.get_exchange_rates(currency='BTC')
rates`
Result:

> <APIObject @ 0x115841468> {
  "currency": "USD",
  "rates": {
    "AED": "3.67",
    "AFN": "69.77",
    "ALL": "109.45"...

I also get similar issues when I try getting the price
`price = client.get_buy_price(currency_pair = 'LTC-USD')
price`
Output 

> <APIObject @ 0x115841fc0> {
  "amount": "13830.94",
  "base": "BTC",
  "currency": "USD"

I am using API keys with all functionality allowed.

**Comment by wasdee** [comment]
Same Here

**Comment by NeoTheThird** [comment]
I can confirm this. Very bad behavior considering just returning USD might cause the client to buy or sell on the assumption of a wrong price!

**Comment by murchie85** [comment]
Where are the developers? This is a key feature in the API integration...

**Comment by wasdee** [comment]
this is 2-year-old last update repository.

**Comment by belese** [comment]
same here. sometimes it's ok, sometimes not.

**Comment by joshblum** [comment]
This should be fixed by #54, @sds can you release a new version to pypi?

**Comment by sds** [comment]
[2.0.7](https://github.com/coinbase/coinbase-python/releases/tag/2.0.7) was released yesterday. Hope this helps!
