### ISSUE TITLE
Assistance with basic beginner question

### ISSUE THREAD

**Issue by wayneworkman** [coinbase/coinbase-python#66]
Hello,
I've created a stackoverflow topic here describing a problem. https://stackoverflow.com/questions/48273396/coinbase-api-python-library-getting-started

I'm trying to just get started with this library but it doesn't seam to work anymore?
Any help would be appreciated.

Thanks,
Wayne

**Comment by wayneworkman** [comment]
Bumping this so it does not go stale. Hopefully the coinbase people will see this and assist.

**Comment by sds** [comment]
Hey @wayneworkman, please try again with version 2.0.7 and open a new issue if you're still encountering problems. Thanks!
