### ISSUE TITLE
always getting error

### ISSUE THREAD

**Issue by ashutoshdev** [coinbase/coinbase-python#73]
{"data": "{\" error \ ": \" invalid_request \ ", \" error_description \ ": \" The request is missing a prescribed parameter, contains an unsupported parameter value, or is different Way buggy. \ "}"}

**Comment by sds** [comment]
Hey @ashutoshdev, it would help if you included a reproducible example to help debug this issue. Have a look at this [similar issue](https://github.com/coinbase/coinbase-ruby/issues/109) on another project to see if it's what you're hitting.

If that doesn't help, we strongly recommend you reach out to our [support team](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-) as they can look at your specific account to see if there's an issue there. This project is intended to address issues with the package itself.

**Comment by ashutoshdev** [comment]
Hey @sds
   Thanks for your reply me I have written issue in support You can not believe they are very slow to give me reply they take 2-3 day to reply me for one response .so you can think about that much they slow in the fast era .Every body doing speed up in every sector .
:-1:    :(
