### ISSUE TITLE
coinbase.wallet.error.ParamRequiredError: APIError(id=param_required): Required parameter missing: to

### ISSUE THREAD

**Issue by awasunyin** [coinbase/coinbase-python#75]
Hi!

I get this following error message:
`coinbase.wallet.error.ParamRequiredError: APIError(id=param_required): Required parameter missing: to`

even though I have provided all the required parameters as defined in your documentation:
```
client.transfer_money(
    account_id,
    to="<coinbase_account_id>",
    amount="1",
    currency="BTC")
```

I have read all the documentation from coinbase: https://developers.coinbase.com/api/v2#errors, as well as searched through other forums and I haven't found any fix to it, only that someone else has also the same issue: https://bitgetter.pro/2017/05/27/getting-errors-when-sending-funds/

Any ideas?
Cheers

**Comment by sds** [comment]
Hey @awasunyin! Sorry for the delay in response.

I'm not able to reproduce this issue with the latest version of this package (2.1.0 at time of writing).

If you're still seeing this issue, can you open a ticket with our [support team](https://support.coinbase.com/) so they can investigate further? 

Thanks!
