### ISSUE TITLE
Random "invalid signature" errors when more than one parameter

### ISSUE THREAD

**Issue by Sovetnikov** [coinbase/coinbase-python#80]
Some time i get strange random "invalid signature" errors on requests with two parameters like this:
client.get_transactions('BTC', starting_after='<guid>', limit=100)
But if limit parameter is omitted all works fine:
client.get_transactions('BTC', starting_after='<guid>')

Cant say exactly where is this problem comes from, but seems that ordering of GET parameters is different on client and on coinbase server and that causes "invalid signature" errors, because GET parameters included in message for signing request.

**Comment by 1000D87** [comment]
1000D

**Comment by sjellish** [comment]
I also get this error under the exact same circumstance as your example. If I try to use a limit of 100 and pagination to get all of my transactions, the first call works, but the second call that includes the starting_after parameter will fail with an invalid signature. If I remove the limit and just use starting_after everything works fine. This code used to work for me but I had not run it in a while. Not sure when it broke.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
