### ISSUE TITLE
Coinbase provides key, but no secret

### ISSUE THREAD

**Issue by scarolan** [coinbase/coinbase-python#90]
I've tried several times to generate a new API key/secret pair using the instructions on your website.  Each time I do it an API key is generated but there is no secret.  Can you please help?  I've tried emailing your help desk but got no response after several emails and requests.

**Comment by iregina** [comment]
The secret is only shown once in a window that pops up and appears only once upon the API creation - could you please try creating a new key and looking for the secret?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
