### ISSUE TITLE
Various Intermittent Request Errors: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

### ISSUE THREAD

**Issue by cgunnels** [coinbase/coinbase-python#91]
Can anyone help me figure out why I'm getting this error?

**Comment by csdenboer** [comment]
I'm having the same issue... Seems to be a problem on Coinbase's side.

**Comment by RomanMelnyk113** [comment]
Same situation... would be appreciated for any help!

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
