### ISSUE TITLE
send_money's idempotence parameter stopped working

### ISSUE THREAD

**Issue by csdenboer** [coinbase/coinbase-python#92]
Recently the idem parameter of the send_money API call seems to have stopped working. Unfortunately, this has resulted in duplicate payments being send by us. For example payment id _fda3e58a-f00e-50eb-91e9-ef299d3818b2_ and _fda60c17-20e3-5003-954a-0cf5e1896cc6_ were created with the idem value. When I inspect the transactions I see two different idem values of which both are 'unknown' at our side. They probably have been generated by Coinbase. This implicates that the idem values that we have passed have been ignored.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
