### ISSUE TITLE
get_address_transactions not working for ethereum and litecoin

### ISSUE THREAD

**Issue by ephraimbuddy** [coinbase/coinbase-python#93]
I receive (NotFoundError) APIError with ID not found when I use `client.get_address_transactions` for ethereum and litecoin addresses.

I receive data when I use bitcoin.
The account IDs used were the same used to create the addresses respectively

**Comment by JetJadeja** [comment]
Has there ever been a solution to this problem?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
